# Generated by Django 5.2 on 2025-06-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPromotionPermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=255)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsor_address', models.TextField()),
                ('sponsor_telephone', models.CharField(blank=True, max_length=50)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254)),
                ('sponsor_authorized_rep', models.CharField(max_length=255)),
                ('sponsor_designation', models.CharField(max_length=255)),
                ('advertising_agency_name', models.CharField(blank=True, max_length=255)),
                ('advertising_agency_address', models.TextField(blank=True)),
                ('advertising_agency_telephone', models.CharField(blank=True, max_length=50)),
                ('advertising_agency_email', models.EmailField(blank=True, max_length=254)),
                ('advertising_agency_authorized_rep', models.CharField(blank=True, max_length=255)),
                ('advertising_agency_designation', models.CharField(blank=True, max_length=255)),
                ('promo_period_start', models.DateField(blank=True, null=True)),
                ('promo_period_end', models.DateField(blank=True, null=True)),
                ('coverage', models.CharField(choices=[('NCR', 'NCR or several regions including Metro Manila'), ('2_REGIONS', '2 regions or more outside NCR'), ('1_REGION_2_PROVINCES', 'Single region covering 2 provinces or more'), ('1_PROVINCE', 'Single province')], max_length=20)),
                ('region_location_of_sponsor', models.CharField(blank=True, max_length=255)),
                ('regions_covered', models.TextField(blank=True)),
                ('single_region', models.CharField(blank=True, max_length=255)),
                ('provinces_covered', models.TextField(blank=True)),
                ('single_province', models.CharField(blank=True, max_length=255)),
                ('cities_or_municipalities_covered', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('specifications', models.TextField(blank=True)),
                ('permit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='documents.salespromotionpermitapplication')),
            ],
        ),
    ]
