# Generated by Django 5.2 on 2025-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespromotionpermitapplication',
            name='date_filed',
        ),
    ]
