# Generated by Django 5.2 on 2025-06-28 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_salespromotionpermitapplication_date_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='date_filed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
