# Generated by Django 5.2 on 2025-07-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_salespromotionpermitapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='personal_data_images')),
                ('position', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
