# Generated by Django 5.2 on 2025-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_personaldatasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatasheet',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personaldatasheet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
    ]
