# Generated by Django 5.2 on 2025-07-09 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_employeebackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_course', models.CharField(max_length=255)),
                ('conducted_by', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('personal_data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_attended', to='documents.personaldatasheet')),
            ],
        ),
    ]
