# Generated by Django 5.2 on 2025-07-09 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_educationalattainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_references', to='documents.personaldatasheet')),
            ],
        ),
    ]
