# Generated by Django 5.2 on 2025-07-12 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_characterreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRepairAccreditationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('NEW', 'New'), ('RENEWAL', 'Renewal')], max_length=10)),
                ('category', models.CharField(choices=[('MOTOR VEHICLES & HEAVY EQUIPMENT', 'Motor Vehicles & Heavy Equipment'), ('MEDICAL & DENTAL EQUIPMENT', 'Medical & Dental Equipment'), ('OFFICE MACHINE/DATA PROCESSING EQUIPMENT', 'Office Machine/Data Processing Equipment'), ('ENGINES & ENGINEERING WORKS (MACHINE SHOPS)', 'Engines & Engineering Works (Machine Shops)'), ('ELECTRONICS, ELECTRICAL, AIRCONDITIONING & REFRIGERATION', 'Electronics, Electrical, Airconditioning & Refrigeration'), ('OTHER CONSUMER MECHANICAL & INDUSTRIAL EQUIPMENT, APPLIANCES OR DEVICES', 'Other Consumer Mechanical & Industrial Equipment, Appliances or Devices')], max_length=100)),
                ('star_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name_of_business', models.CharField(max_length=255)),
                ('building_name_or_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city_or_municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=40)),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('social_classification', models.CharField(choices=[('ABLED', 'Abled'), ('PWD', 'Differently Abled'), ('IP', 'Indigenous Person'), ('SENIOR', 'Senior Citizen'), ('YOUTH', 'Youth'), ('OSY', 'Out-of-School Youth')], max_length=10)),
                ('asset_size', models.CharField(choices=[('MICRO', 'Micro (<Php3M)'), ('SMALL', 'Small (Php3M - <15M)'), ('MEDIUM', 'Medium (Php15M - 100M)'), ('LARGE', 'Large (>Php100M)')], max_length=10)),
                ('form_of_organization', models.CharField(choices=[('SP', 'Single Proprietorship'), ('CORP', 'Corporation'), ('PARTNERSHIP', 'Partnership'), ('COOP', 'Cooperative')], max_length=20)),
                ('industry_classification', models.TextField()),
                ('annual_gross_service_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('capital_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_identification_number', models.CharField(max_length=20)),
                ('date_established', models.DateField()),
                ('total_employees', models.PositiveIntegerField()),
                ('warranty_period', models.PositiveIntegerField(default=0, help_text='Number of days warranty is valid')),
            ],
        ),
    ]
