# Generated by Django 5.2 on 2025-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_servicerepairaccreditationapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='annual_gross_service_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='capital_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='industry_classification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
