# Generated by Django 5.2 on 2025-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_servicerepairaccreditationapplication_annual_gross_service_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='industry_classification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
