# Generated by Django 5.2 on 2025-07-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_servicerepairaccreditationapplication_star_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalattainment',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='employeebackground',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='trainingsattended',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='annual_gross_service_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='As of 31 December 20__', max_digits=15, null=True),
        ),
    ]
