# Generated by Django 5.2 on 2025-07-23 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_educationalattainment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField(max_length=255)),
                ('account_officer_date', models.DateField(blank=True, null=True)),
                ('account_officer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('special_collecting_officer_date', models.DateField(blank=True, null=True)),
                ('special_collecting_officer_or_number', models.CharField(blank=True, max_length=50)),
                ('special_collecting_officer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='PermitFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('discount', 'Discount'), ('premium', 'Premium'), ('raffle', 'Raffle'), ('contest', 'Contest'), ('redemption', 'Redemption'), ('games', 'Games'), ('beauty_contest', 'Beauty Contest'), ('home_solicitation', 'Home Solicitation'), ('amendments', 'Amendments'), ('doc_stamp', 'DocStamp')], max_length=20)),
                ('remarks', models.CharField(choices=[('R', 'Several provinces/cities within a region'), ('P', 'Single province/city/municipality'), ('X', '2 or more regions excluding Metro Manila'), ('A', 'Additional fees due to reassessment of premium and prizes')], max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='documents.salespromotionpermitapplication')),
            ],
        ),
    ]
