# Generated by Django 5.2 on 2025-07-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_service_servicecategory_inspectionvalidationreport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderofpayment',
            options={'verbose_name_plural': 'Orders of Payment'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='trainingsattended',
            options={'verbose_name_plural': 'Trainings Attended'},
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='is_branch',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='is_main_office',
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='types_of_office_shop',
            field=models.CharField(choices=[('Main', 'Main'), ('Branch', 'Branch')], default='Main', max_length=30),
        ),
    ]
