# Generated by Django 5.2 on 2025-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_orderofpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='accreditation_cert',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Accreditation Certificate', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='accreditation_cert_remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='business_name_cert',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Business Name Certificates', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='business_name_cert_remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='service_rates_remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='types_of_office_shop',
            field=models.CharField(choices=[('Main', 'Main'), ('Branch', 'Branch')], default='Main', help_text='Type of Office/Shop', max_length=30),
        ),
    ]
