# Generated by Django 5.2 on 2025-07-25 01:03

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_inspectionvalidationreport_accreditation_cert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionvalidationreport',
            options={'ordering': ['-date'], 'verbose_name': 'Inspection and Validation Report', 'verbose_name_plural': 'Inspection and Validation Reports'},
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='accreditation_cert',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Accreditation Certificate', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='accreditation_cert_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='business_name_cert',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Business Name Certificates', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='business_name_cert_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_documented',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_no',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_yes',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='continuous_training_program',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='customer_satisfaction_feedback_form_no',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='customer_satisfaction_feedback_form_yes',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='customers_reception_waiting_area_adequate',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='customers_reception_waiting_area_existing',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='existing_record_keeping_system',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='list_employees_past_2_years',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='medical_kit_available',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='racmac_sres_recovery_machine',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='record_keeping_suitable',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='refrigerant_storage_disposal_system',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='service_rates',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='service_rates_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='tool_equipment_storage_adequate',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='tool_equipment_storage_existing',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='tools_equipment_complete',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='type_of_application_activity',
            field=models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal'), ('monitoring', 'Monitoring')], max_length=50),
        ),
    ]
