# Generated by Django 5.2 on 2025-07-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_inspectionvalidationreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='inspection_validation_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='documents.inspectionvalidationreport'),
        ),
    ]
