# Generated by Django 5.2 on 2025-07-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_servicecategory_inspection_validation_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='inspection_validation_report',
        ),
        migrations.AddField(
            model_name='service',
            name='inspection_validation_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='documents.inspectionvalidationreport'),
        ),
    ]
