# Generated by Django 5.2 on 2025-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_remove_servicecategory_inspection_validation_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='inspection_validation_report',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='key',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('aircon_refrigeration', 'Aircon/Refrigeration'), ('office_machines', 'Office Machines'), ('motor_vehicles', 'Motor Vehicles and Heavy Equipment'), ('wheel_services', 'Complete Wheel Services'), ('engineering_works', 'Engines and Engineering Works (Machine Shops)'), ('welding', 'Welding Services')], max_length=50, unique=True),
        ),
    ]
