# Generated by Django 5.2 on 2025-07-28 23:55

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_remove_service_inspection_validation_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='racmac_serial_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='racmac_sres_recovery_machine',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='For RAC/MAC SREs, with recovery machine', max_length=3),
        ),
    ]
