# Generated by Django 5.2 on 2025-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_inspectionvalidationreport_racmac_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='proof_acquisition_recovery_machine',
            field=models.CharField(blank=True, help_text='Proof of acquisition of recovery machine', max_length=255),
        ),
    ]
