# Generated by Django 5.2 on 2025-07-29 00:08

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_inspectionvalidationreport_proof_acquisition_recovery_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='tesda_certification_coc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='continuous_training_program',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='For RAC/MAC, with continuous training program for mechanics/technicians?', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='list_employees_past_2_years',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Has submitted trainings of employees for the past 2 years?', max_length=3),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='refrigerant_storage_disposal_system',
            field=models.CharField(blank=True, help_text='For RAC/MAC, with refrigerant recovery storage and disposal system consistent with existing enivronmental laws and regulations', max_length=255, null=True),
        ),
    ]
