# Generated by Django 5.2 on 2025-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_remove_inspectionvalidationreport_medical_kit_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='type_of_insurance_coverage',
            field=models.CharField(blank=True, help_text='Type of Insurance Coverage?', max_length=255),
        ),
    ]
