# Generated by Django 5.2 on 2025-07-29 00:37

import documents.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_inspectionvalidationreport_type_of_insurance_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_documented',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_no',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_yes',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='customer_satisfaction_feedback_form_no',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='customer_satisfaction_feedback_form_yes',
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_documented',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Documented?', max_length=3),
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='complaints_handling_process_exists',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='With complaints handling process?', max_length=3),
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='customer_satisfaction_feedback_form_exists',
            field=documents.models.YesNoField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='With customer satisfaction feedback? (CSF)', max_length=3),
        ),
    ]
