# Generated by Django 5.2 on 2025-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_remove_inspectionvalidationreport_complaints_handling_documented_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_approval',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_continuing_accreditation',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_disapproval',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_monitoring_issuance_sco',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_new_application',
        ),
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='recommendation_renewal_application',
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('approval', 'Approval'), ('disapproval', 'Disapproval'), ('monitoring', 'Monitoring/Issuance of SCO'), ('new_application', 'New Application'), ('renewal', 'Renewal Application'), ('continuing_accreditation', 'Continuing Accreditation')], max_length=50, null=True),
        ),
    ]
