# Generated by Django 5.2 on 2025-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_remove_inspectionvalidationreport_recommendation_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionvalidationreport',
            name='certification_text',
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='inspected_by_accreditation_officer',
            field=models.CharField(blank=True, help_text='Inspected by: (Accreditation Officer/Leader)', max_length=255),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='inspected_by_member',
            field=models.CharField(blank=True, help_text='Inspected by: (Member)', max_length=255),
        ),
    ]
