# Generated by Django 5.2 on 2025-07-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_remove_inspectionvalidationreport_certification_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='findings_remarks',
            field=models.TextField(blank=True, help_text='Findings/Remarks'),
        ),
    ]
