# Generated by Django 5.2 on 2025-08-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_alter_inspectionvalidationreport_findings_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEvaluationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=255)),
                ('type_of_application', models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal')], max_length=50)),
                ('renewal_due_date', models.DateField(blank=True, help_text='Date Expired: Dec 31', null=True)),
                ('star_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='permitfee',
            name='permit',
        ),
        migrations.AddField(
            model_name='permitfee',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='documents.orderofpayment'),
        ),
        migrations.CreateModel(
            name='RequirementChecklisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('req_1', "Original/e-copy notarized completely filled out application form with Undertaking/Warranty (Minimum of 90 days) signed by the owner or authorized agent (signed by the proprietor for SPP, if other than the Proprietor, attach SPA/Authorization: President/Managing Partner for Corporation/Partnership, otherwise, copy of Board Resolution/Secretary's Certificate with authorized signatory)"), ('req_2', 'Copy of Valid Business Name Certificate of Registration for Single Proprietorship or Certified true copy of company Partnership and Articles of Incorporation/Partnership for Corporation/Partnership, GDA certificate of registration and Articles of Cooperation for Cooperatives, SEC Registration Certificate only, if no amendments made in Albay Ps'), ('req_3', 'Copy of Latest Accreditation Certificate'), ('req_4', 'Original-copy Certified List of Mechanics/Technicians and Position with Personnel/no Data Sheet'), ('req_5', 'Copy of valid and relevant TESDA Certificate (National Certificate or Certificate of Competency for Technical Employees)'), ('req_6', 'Original/e-copy Certified List of Trainings Attended by the Employees/Technicians within the past 2 years'), ('req_7', 'Original/e-copy List of Shop Tools and Equipment'), ('req_8', 'Original/e-copy Shop Floor Plan/Layout/Size/No. of Stalls/Working Bays and interior pictures of the Shop/Office – showing front (with signages) and interior/working area'), ('req_9', 'Originally issued Certification (in lieu of items 6 and 8) that there are no changes on the said items for renewals, provided that said requirements have been previously submitted'), ('req_10', "Copy of Comprehensive Insurance Policy covering the customer's motor vehicle while in custody and use against theft, pilferage, fire, flood and loss. Insurance coverage must be P100,000.00 year and its expiry date must be on or after December 31st 20__, and copy of official receipt (proof of payment of insurance premiums)"), ('req_11', "Original Affidavit stating that all services and repairs are done in the clients presence and that they conduct all services and repairs in their client's premises. (In lieu of insurance policy)"), ('req_12', 'In places where there are no insurance companies willing to undertake the risk due to the peace and order situation in the area the Director may grant exemption upon sufficient proof of such circumstances'), ('req_13', 'Copy of valid dealership agreement (five star only) Motor Vehicle, Ref and Aircon, Office Machine/Data Processing Equipment)'), ('req_14', 'Copy of Valid Contract of Service, (if any)'), ('req_15', 'Original copy of Performance Bond policy and official receipt with minimum coverage of P50,000. (in favor of the DTI valid up to December 31, 20__ for 3 to 5 STAR, New or Renewal)')], max_length=255)),
                ('remarks', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_item', to='documents.checklistevaluationsheet')),
            ],
        ),
    ]
