# Generated by Django 5.2 on 2025-08-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_checklistevaluationsheet_remove_permitfee_permit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofpayment',
            name='amendments_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='amendments_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='beauty_contest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='beauty_contest_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='contest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='contest_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='discount_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='doc_stamp_amount',
            field=models.DecimalField(decimal_places=2, default=30.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='doc_stamp_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='games_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='games_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='home_solicitation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='home_solicitation_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='premium_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='raffle_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='raffle_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='redemption_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='redemption_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PermitFee',
        ),
    ]
