# Generated by Django 5.2 on 2025-08-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_orderofpayment_amendments_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofpayment',
            name='amendments_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amendments amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='amendments_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='beauty_contest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='beauty_contest amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='beauty_contest_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='contest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='contest amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='contest_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='discount amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='discount_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='doc_stamp_amount',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='doc_stamp_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='games_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='games amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='games_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='home_solicitation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='home_solicitation amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='home_solicitation_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='premium amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='premium_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='raffle_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='raffle amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='raffle_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='redemption_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='redemption amount in ₱', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='redemption_remark',
            field=models.CharField(blank=True, choices=[('applicable_only', 'applicable only for ref/aircon shops'), ('not_applicable_if_no_changes', 'not applicable, if no changes'), ('not_applicable_if_not_charges', 'not applicable, if not charges'), ('not_applicable', 'not applicable'), ('see_attached_sample_form', 'see attached sample form'), ('applicable_only_for_5_star', 'applicable only for 5 star application'), ('not_applicable_for_one_and_two_star', 'not applicable for one & two star application')], max_length=255, null=True),
        ),
    ]
