# Generated by Django 5.2 on 2025-08-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_alter_orderofpayment_amendments_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofpayment',
            name='amendments_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='beauty_contest_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='contest_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='discount_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='games_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='home_solicitation_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='premium_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='raffle_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='redemption_remark',
            field=models.CharField(blank=True, choices=[('R', 'R - Several provinces / cities / municipalities within a single region'), ('P', 'P - Single province / city / municipality'), ('X', 'X - 2 or more regions excluding Metro Manila'), ('A', 'A - Additional fees due to reassessment of premium and prizes')], max_length=255, null=True),
        ),
    ]
