# Generated by Django 5.2 on 2025-08-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_alter_orderofpayment_amendments_remark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementChecklisItem',
        ),
    ]
