# Generated by Django 5.2 on 2025-08-07 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_checklistevaluationsheet_req_affidavit_on_site_repairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistevaluationsheet',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
