# Generated by Django 5.2 on 2025-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_alter_checklistevaluationsheet_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of days warranty is valid', null=True),
        ),
    ]
