# Generated by Django 5.2 on 2025-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_alter_servicerepairaccreditationapplication_warranty_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='annual_gross_service_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Gross Service Revenue (as of Dec 31, 20__)', max_digits=15, null=True),
        ),
    ]
