# Generated by Django 5.2 on 2025-08-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_alter_servicerepairaccreditationapplication_annual_gross_service_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region (NCR)'), ('CAR', 'Cordillera Administrative Region (CAR)'), ('Region I', 'Ilocos Region (Region I)'), ('Region II', 'Cagayan Valley (Region II)'), ('Region III', 'Central Luzon (Region III)'), ('Region IV-A', 'CALABARZON (Region IV-A)'), ('MIMAROPA', 'MIMAROPA Region'), ('Region V', 'Bicol Region (Region V)'), ('Region VI', 'Western Visayas (Region VI)'), ('Region VII', 'Central Visayas (Region VII)'), ('Region VIII', 'Eastern Visayas (Region VIII)'), ('Region IX', 'Zamboanga Peninsula (Region IX)'), ('Region X', 'Northern Mindanao (Region X)'), ('Region XI', 'Davao Region (Region XI)'), ('Region XII', 'SOCCSKSARGEN (Region XII)'), ('Region XIII', 'Caraga (Region XIII)'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)')], max_length=255),
        ),
    ]
