# Generated by Django 5.2 on 2025-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_personaldatasheet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistevaluationsheet',
            options={'verbose_name': 'Checklist of Requirements and Evaluation Sheet', 'verbose_name_plural': 'Checklist of Requirements and Evaluation Sheets'},
        ),
        migrations.AlterModelOptions(
            name='personaldatasheet',
            options={'verbose_name': 'Personal Data Sheet', 'verbose_name_plural': 'Personal Data Sheets'},
        ),
        migrations.AlterModelOptions(
            name='salespromotionpermitapplication',
            options={'verbose_name': 'Sales Promotion Permit Application', 'verbose_name_plural': 'Sales Promotion Permit Applications'},
        ),
        migrations.AlterModelOptions(
            name='servicerepairaccreditationapplication',
            options={'verbose_name': 'Accreditation of Service and Repair Enterprise', 'verbose_name_plural': 'Accreditation of Service and Repair Enterprises'},
        ),
    ]
