# Generated by Django 5.2 on 2025-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_alter_checklistevaluationsheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalattainment',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='employeebackground',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='checklistevaluationsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionvalidationreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='personaldatasheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
    ]
