# Generated by Django 5.2 on 2025-08-31 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0046_alter_educationalattainment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistevaluationsheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
