# Generated by Django 5.2 on 2025-09-01 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_checklistevaluationsheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldatasheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
