# Generated by Django 5.2 on 2025-09-01 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_personaldatasheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
