# Generated by Django 5.2 on 2025-09-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_servicerepairaccreditationapplication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistevaluationsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldatasheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
