# Generated by Django 5.2 on 2025-09-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0051_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofpayment',
            name='special_collecting_officer_or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
