# Generated by Django 5.2 on 2025-10-17 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0056_alter_checklistevaluationsheet_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('official_receipt_number', models.CharField(max_length=50)),
                ('rc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payor', models.CharField(max_length=255)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stamp_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bn_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bn_renewal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accreditation_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accreditation_renewal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accreditation_filing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('truck_rebuilding_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('truck_rebuilding_renewal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_promo_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_promo_revisions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('certification', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bulk_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assessment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('license_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('petc_accreditation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bn_listings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confiscated_materials', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fines_penalties', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surcharge_bn_reg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surcharge_accre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unserviceable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('misc_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
