# Generated by Django 5.2 on 2025-10-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0057_collectionreportitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionreportitem',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectionreportitem',
            name='payor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
