# Generated by Django 5.2 on 2025-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0058_alter_collectionreportitem_particulars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreportitem',
            name='official_receipt_number',
        ),
        migrations.AddField(
            model_name='collectionreportitem',
            name='number',
            field=models.CharField(blank=True, help_text='Official Receipt Number', max_length=50),
        ),
    ]
