# Generated by Django 5.2 on 2025-10-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0059_remove_collectionreportitem_official_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionreportitem',
            name='number',
            field=models.CharField(blank=True, help_text='Official Receipt Number', max_length=50, null=True),
        ),
    ]
