# Generated by Django 5.2 on 2025-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0060_alter_collectionreportitem_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_items', models.ManyToManyField(related_name='collection_reports', to='documents.collectionreportitem')),
            ],
        ),
    ]
