# Generated by Django 5.2 on 2025-10-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_collectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
