# Generated by Django 5.2 on 2025-10-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0062_collectionreport_date_from_collectionreport_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='certification_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='collecting_officer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='official_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='special_collecting_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='special_collecting_officer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total_collections',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='undeposited_collections',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
