# Generated by Django 5.2 on 2025-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0063_collectionreport_certification_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreportitem',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
