# Generated by Django 5.2 on 2025-10-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0064_collectionreportitem_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreport',
            name='certification_text',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='collecting_officer_name',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='official_designation',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='special_collecting_officer',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='special_collecting_officer_date',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='total_collections',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='undeposited_collections',
        ),
        migrations.RemoveField(
            model_name='collectionreportitem',
            name='deposit',
        ),
    ]
