# Generated by Django 5.2 on 2025-10-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0065_remove_collectionreport_certification_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreportitem',
            name='surcharge_accre',
        ),
        migrations.RemoveField(
            model_name='collectionreportitem',
            name='unserviceable',
        ),
        migrations.AddField(
            model_name='collectionreportitem',
            name='surchage_accreditation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge Accreditation', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='collectionreportitem',
            name='bn_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BN Original', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='collectionreportitem',
            name='bn_renewal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BN Renewal', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='collectionreportitem',
            name='fines_penalties',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fines and Penalties (629)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='collectionreportitem',
            name='surcharge_bn_reg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge BN Registration', max_digits=12, null=True),
        ),
    ]
