# Generated by Django 5.2 on 2025-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0066_remove_collectionreportitem_surcharge_accre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='dti_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='name_of_collecting_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='official_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='report_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='report_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='undeposited_last_report',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Undeposited Collections Last Report', max_digits=12, null=True),
        ),
    ]
