# Generated by Django 5.2 on 2025-10-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0067_collectionreport_certification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionreport',
            old_name='name_of_collecting_officer',
            new_name='name_and_signature_of_collecting_officer',
        ),
    ]
