# Generated by Django 5.2.7 on 2025-10-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0068_orderofpayment_sales_promotion_permit_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
