# Generated by Django 5.2.7 on 2025-10-21 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0068_orderofpayment_sales_promotion_permit_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofpayment',
            name='payment_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting Payment'), ('paid', 'Paid'), ('verified', 'Verified')], default='awaiting', max_length=20),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
