# Generated by Django 5.2 on 2025-10-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0068_rename_name_of_collecting_officer_collectionreport_name_and_signature_of_collecting_officer'),
        ('documents', '0069_orderofpayment_payment_status_and_more'),
    ]

    operations = [
    ]
