# Generated by Django 5.2 on 2025-10-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_orderofpayment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreport',
            name='name_of_collecting_officer',
        ),
    ]
