# Generated by Django 5.2 on 2025-10-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0070_merge_20251021_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionreport',
            old_name='name_and_signature_of_collecting_officer',
            new_name='name_and_signature_of_collection_officer',
        ),
    ]
