# Generated by Django 5.2 on 2025-10-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0070_remove_collectionreport_name_of_collecting_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='name_of_collection_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
