# Generated by Django 5.2 on 2025-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0073_alter_personaldatasheet_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionreport',
            options={'ordering': ['-report_collection_date']},
        ),
        migrations.AlterField(
            model_name='collectionreport',
            name='report_collection_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionreport',
            name='report_items',
            field=models.ManyToManyField(blank=True, related_name='collection_reports', to='documents.collectionreportitem'),
        ),
        migrations.AlterField(
            model_name='collectionreport',
            name='report_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='collectionreport',
            index=models.Index(fields=['-report_collection_date'], name='documents_c_report__12b8d4_idx'),
        ),
    ]
