# Generated by Django 5.2 on 2025-10-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0074_alter_collectionreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='responsibility_center_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
