# Generated by Django 5.2 on 2025-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0075_collectionreport_responsibility_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='collections_this_report',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Collections per OR Numbers: ', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='undeposited_this_report',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Undeposited Collections This Report', max_digits=12, null=True),
        ),
    ]
