# Generated by Django 5.2.7 on 2025-10-27 15:05

import documents.models.sales_promotion_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0076_collectionreport_collections_this_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofpayment',
            name='acknowledgment_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderofpayment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='reference_code',
            field=models.CharField(default=documents.models.sales_promotion_model.SalesPromotionPermitApplication.generate_reference_code, max_length=20, unique=True),
        ),
    ]
