# Generated by Django 5.2 on 2025-10-28 00:29

import documents.models.sales_promotion_model
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0077_orderofpayment_acknowledgment_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='reference_code',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                default=documents.models.sales_promotion_model.generate_reference_code,
            ),
        ),
    ]
