# Generated by Django 5.2.7 on 2025-10-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0077_orderofpayment_acknowledgment_generated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderofpayment',
            old_name='payment_code',
            new_name='reference_code',
        ),
        migrations.RemoveField(
            model_name='salespromotionpermitapplication',
            name='reference_code',
        ),
    ]
