# Generated by Django 5.2.7 on 2025-11-23 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0078_rename_payment_code_orderofpayment_reference_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessScopeUpdateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('name_of_business', models.CharField(max_length=255)),
                ('type_of_application', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('city_or_municipality', 'City/Municipality'), ('barangay', 'Barangay')], max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Business Scope Form',
                'verbose_name_plural': 'Update Business Scope Forms',
            },
        ),
    ]
