# Generated by Django 5.2.7 on 2025-11-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0079_businessscopeupdatemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessscopeupdatemodel',
            old_name='type_of_application',
            new_name='scope',
        ),
    ]
