# Generated by Django 5.2.7 on 2025-11-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0080_rename_type_of_application_businessscopeupdatemodel_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessScopeUpdateModel',
        ),
    ]
