# Generated by Django 5.2.7 on 2025-11-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0081_delete_businessscopeupdatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBusinessNameRelatedFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_unpaid', 'Submitted (Unpaid)'), ('submitted_paid', 'Submitted (Paid)'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('type', models.CharField(choices=[('bn_certification', 'BN Certification'), ('authentication', 'Authentication/Certified True Copy (CTC) of BN Certificate of Registration'), ('change_in_territorial_scope', 'Change in Territorial Scope'), ('change_of_business_information', 'Change of Business Information'), ('cancellation', 'Cancellation of Business Name Registration')], max_length=50)),
                ('name_of_business', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_registered', models.DateField()),
                ('trn_ref_code', models.CharField(max_length=16, verbose_name='TRN/Reference Code')),
                ('valid_id_presented', models.ImageField(upload_to='valid_ids', verbose_name='Valid Id Presented')),
                ('bn_certification_purpose', models.TextField(blank=True, null=True, verbose_name='State Purpose')),
                ('no_of_copies', models.PositiveIntegerField(blank=True, null=True)),
                ('change_territorial_scope', models.BooleanField(default=False)),
                ('territorial_scope_from', models.CharField(blank=True, max_length=255, null=True)),
                ('territorial_scope_to', models.CharField(blank=True, max_length=255, null=True)),
                ('change_owner_name', models.BooleanField(default=False)),
                ('owner_name_from', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name_to', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name_proof_basis', models.FileField(blank=True, null=True, upload_to='proof_documents', verbose_name='Proof/Basis (Duplicate or Clear Certified Copy)')),
                ('change_business_address', models.BooleanField(default=False)),
                ('business_address_from', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address_to', models.CharField(blank=True, max_length=255, null=True)),
                ('change_owner_address', models.BooleanField(default=False)),
                ('owner_address_from', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_address_to', models.CharField(blank=True, max_length=255, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Basis/Reason for cancellation')),
            ],
            options={
                'verbose_name': 'Other Business Name Related Form',
                'verbose_name_plural': 'Other Business Name Related Forms',
            },
        ),
    ]
