# Generated by Django 5.2.7 on 2025-11-23 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0082_otherbusinessnamerelatedformmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherbusinessnamerelatedformmodel',
            old_name='contact_number',
            new_name='certificate_number',
        ),
        migrations.AddField(
            model_name='otherbusinessnamerelatedformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
