# Generated by Django 5.2.7 on 2025-11-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0083_rename_contact_number_otherbusinessnamerelatedformmodel_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherbusinessnamerelatedformmodel',
            name='territorial_scope_from',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('regional', 'Regional'), ('city_or_municipality', 'City/Municipality'), ('barangay', 'Barangay')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherbusinessnamerelatedformmodel',
            name='territorial_scope_to',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('regional', 'Regional'), ('city_or_municipality', 'City/Municipality'), ('barangay', 'Barangay')], max_length=255, null=True),
        ),
    ]
