# Generated by Django 5.2.7 on 2025-11-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0084_alter_otherbusinessnamerelatedformmodel_territorial_scope_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherbusinessnamerelatedformmodel',
            name='type',
        ),
    ]
