# Generated by Django 5.2 on 2025-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-avatar-icon.jpg', upload_to='profile_pictures/'),
        ),
    ]
