# Generated by Django 5.2 on 2025-08-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('admin', 'Admin')], default='business_owner', max_length=20),
        ),
    ]
