# Generated by Django 5.2 on 2025-09-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('admin', 'Admin'), ('collection_agent', 'Collection Agent')], default='business_owner', max_length=20),
        ),
    ]
