# Generated by Django 5.2 on 2025-09-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
        ('users', '0005_user_default_address_user_default_phone'),
    ]

    operations = [
    ]
