# Generated by Django 5.2 on 2025-10-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dti_office',
            field=models.CharField(blank=True, help_text='Only applicable if the user is a collection agent.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='official_designation',
            field=models.CharField(blank=True, help_text='Only applicable if the user is a collection agent.', max_length=100, null=True),
        ),
    ]
