# Generated by Django 5.2.7 on 2025-10-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
